# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Generate < Formula
  desc "generate is a CLI tool for quickly generating test data such as IBAN numbers, UUIDs, VAT numbers and random passwords"
  homepage "https://github.com/f-lombardo/generate"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.1/generate_0.0.1_darwin_amd64.tar.gz"
      sha256 "9cbf3fc74f552c9055aaf12bc4a94ca165c155c77a857f832ac56d7c8dbae8a1"

      define_method(:install) do
        bin.install "generate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.1/generate_0.0.1_darwin_arm64.tar.gz"
      sha256 "7b5001a0239b79e5a3d3c17c49f1a573043e2ee21f8c4f72d6bce4b047d14c1d"

      define_method(:install) do
        bin.install "generate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.1/generate_0.0.1_linux_amd64.tar.gz"
      sha256 "255be14480cc125a5c9cede1673868d53bb37aad9700fabacdbab1874a77b1f4"
      define_method(:install) do
        bin.install "generate"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.1/generate_0.0.1_linux_armv6.tar.gz"
      sha256 "721205799b9ea8efa7362415bf82edd6f33bef9256f8b54ef87cd734a067dccf"
      define_method(:install) do
        bin.install "generate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.1/generate_0.0.1_linux_arm64.tar.gz"
      sha256 "eccd194d7b820331dc1551bf546ff0bed48643d1ad3144139fe36921f448d2a5"
      define_method(:install) do
        bin.install "generate"
      end
    end
  end
end
