# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Generate < Formula
  desc "generate is a CLI tool for quickly generating test data such as IBAN numbers, UUIDs, VAT numbers and random passwords"
  homepage "https://github.com/f-lombardo/generate"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.0/generate_0.0.0_darwin_amd64.tar.gz"
      sha256 "7eaed829dc62d45587318915ee2e2651f3e894a9cb41de7d6fd58fa2ca9069c4"

      define_method(:install) do
        bin.install "generate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.0/generate_0.0.0_darwin_arm64.tar.gz"
      sha256 "bc474b6683c13dbd68f50eb1b0394e2f8150be3a4b55e2ad025bcbfea64d51fe"

      define_method(:install) do
        bin.install "generate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.0/generate_0.0.0_linux_amd64.tar.gz"
      sha256 "a938ba8d3b3124cc6232e6b13b7ac467b001d9626ab5dc848a6fae74d7c274f2"
      define_method(:install) do
        bin.install "generate"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.0/generate_0.0.0_linux_armv6.tar.gz"
      sha256 "0fb31a8d60814d123ca55dac3c6b0394f64f170e9963600abd72595a20f608d4"
      define_method(:install) do
        bin.install "generate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/f-lombardo/generate/releases/download/0.0.0/generate_0.0.0_linux_arm64.tar.gz"
      sha256 "ed4c80c91301a4d856f12143fe873a12a799ede96df0b30fdb238e314beb51f7"
      define_method(:install) do
        bin.install "generate"
      end
    end
  end
end
